version: '3.1'
services:

  workflows-workshop:
    # build: .
    image: workflows-workshop:latest
    restart: always
    user: root
    environment:
      # - NB_UID=1001
      - GRANT_SUDO=yes
    ports:
      - 8888:8888
    depends_on:
      - mongo
    volumes:
      - ./tutorials:/home/jovyan/tutorials

  mongo:
    image: mongo
    restart: always
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=secret
    # ports:
    #   - 27017:27017  # opening port for development only!
    volumes:
      - ./db:/data/db

  # mongo-express:  # mongo-express only for development only!
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
  #   depends_on:
  #     - mongo
