version: '3.1'
services:

  workflows-workshop:
    image: workflows-workshop:latest
    restart: always
    environment:
      - OMPI_MCA_btl_vader_single_copy_mechanism=none
    ports:
      - 8888:8888
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    restart: always
